version: "3.4"

services:

    web:
        build:
          context: ../MarketPlace-Web
          dockerfile: Dockerfile
        ports:
          - "4200:80"

    api:
        build:
          context: ./
          dockerfile: Dockerfile
        ports:
          - "5010:5010"
        depends_on:
          - db

    db:
        image: "mcr.microsoft.com/azure-sql-edge:latest"
        ports:
          - "1433:1433"

        environment:
            SA_PASSWORD: "Link3721840"
            ACCEPT_EULA: "Y"